[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
spin = "0.9.4"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
kapi = { path = "kapi" }
kutil = { path = "kutil" }

[workspace]
members = [
    "kapi",
    "kutil",
]